#
# Copyright (c) 2022 Sung Ho Park and CSOS
#
# SPDX-License-Identifier: Apache-2.0
#

CONFIG_DIR ?= ../app
CONFIG_NAME ?= arduino_adafruit_battery_sh110x_adafruitnrf52840e

include makefile.mk

